name: End-to-End Tests

on:
    pull_request:
    push:
        branches:
            - trunk

jobs:
    e2e-puppeteer:
        name: Puppeteer - ${{ matrix.part }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                part: [1, 2, 3]
                totalParts: [3]

        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                ref: trunk
            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '18'
            - uses: pnpm/action-setup@v2
              with:
                version: 8
            - name: Install dependencies
              run: pnpm install --no-frozen-lockfile
            - name: Npm build
              run: npm run build
            - name: Install WordPress
              run: |
                  npm run env:start
            - name: Running the tests
              run: |
                  npx wp-scripts test-e2e --config=./packages/e2e-tests/jest.config.js --listTests > ~/.jest-e2e-tests
                  npx wp-scripts test-e2e --config=./packages/e2e-tests/jest.config.js --cacheDirectory="$HOME/.jest-cache" --runTestsByPath $( awk 'NR % ${{ matrix.totalParts }} == ${{ matrix.part }} - 1' < ~/.jest-e2e-tests )

            - name: Archive debug artifacts (screenshots, HTML snapshots)
              uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
              if: always()
              with:
                  name: failures-artifacts
                  path: artifacts
                  if-no-files-found: ignore

            - name: Archive flaky tests report
              uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
              if: always()
              with:
                  name: flaky-tests-report
                  path: flaky-tests
                  if-no-files-found: ignore

    e2e-playwright:
        name: Playwright - ${{ matrix.part }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                part: [1, 2, 3, 4]
                totalParts: [4]

        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                ref: trunk
            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '18'
            - uses: pnpm/action-setup@v2
              with:
                version: 8
            - name: Install dependencies
              run: pnpm install --no-frozen-lockfile

            - name: Npm build
              run: npm run build

            - name: Install Playwright dependencies
              run: |
                  npx playwright install chromium firefox webkit --with-deps

            - name: Install WordPress and start the server
              run: |
                  npm run env:start

            - name: Run the tests
              run: |
                  xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm run test:e2e:playwright -- --shard=${{ matrix.part }}/${{ matrix.totalParts }}

            - name: Archive debug artifacts (screenshots, traces)
              uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
              if: always()
              with:
                  name: failures-artifacts
                  path: artifacts/test-results
                  if-no-files-found: ignore

            - name: Archive flaky tests report
              uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
              if: always()
              with:
                  name: flaky-tests-report
                  path: flaky-tests
                  if-no-files-found: ignore

