name: Static Linting

on:
    pull_request:
    push:
        branches:
            - trunk

jobs:
    php:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Install dependencies
              uses: php-actions/composer@v6
            - name: Lint PHP files
              run: composer run lint

        name: PHP Files

    other:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x, 16.x]

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              run: npm ci
            - name: Lint JavaScript files
              run: npm run lint:js
            - name: Lint CSS files
              run: npm run lint:css
            - name: Lint package.json files
              run: npm run lint:pkg-json
              env:
                  CI: true

        name: Javascript, CSS, and package.json
